# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdje', '0003_auto_20170425_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
